# Generated by Django 6.0.2 on 2026-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
