# Generated by Django 6.0.2 on 2026-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
