# Generated by Django 6.0.2 on 2026-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_customuser_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/'),
        ),
    ]
