# Generated by Django 6.0.2 on 2026-02-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0004_customuser_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cover_photo',
        ),
    ]
