# Generated by Django 6.0.2 on 2026-02-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_remove_customuser_background_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBookList',
            new_name='BookShelf',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
    ]
