# Generated by Django 6.0.2 on 2026-02-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0006_rename_userbooklist_bookshelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='comment',
            field=models.CharField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'Completed'), ('r', 'Reading'), ('d', 'Dropped'), ('t', 'TBR')], default='c', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='type',
            field=models.CharField(blank=True, choices=[('b', 'Book'), ('a', 'Audiobook')], default='b', verbose_name='Type'),
        ),
    ]
