# Generated by Django 6.0.2 on 2026-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0008_alter_bookshelf_comment_alter_bookshelf_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Rating'),
        ),
    ]
