# Generated by Django 6.0.2 on 2026-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0009_alter_bookshelf_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='booklist.bookshelf'),
        ),
    ]
